### PR TITLE
Using of alias

### PR DESCRIPTION
**Pull request by bmaschio**
Added description on how to use Aliasing in HTTP call

### CODE REVIEW

**Comment by fmontesi** [comment]
@thesave What do you think?

**Comment by thesave** [comment]
Thanks for the PR @bmaschio :)

We definitely need to create a page on interactions with REST APIs, possibly extracting topics and examples from [Fabrizio's paper](https://arxiv.org/pdf/1410.3712.pdf). I took the opportunity to create a dedicated page under path `documentation/web_applications/rest-apis-publication-and-integration.md`. I also added some draft/tentative sections that should contain said material.

Please @bmaschio, can you send a new PR where the content of the current PR is in that new page? E.g., under the From REST Resources to Jolie Operations section.

**Comment by bmaschio** [comment]
@thesave The PR was generated from the @fmontesi paper that I use as a reference when I work with HTTP both as a client that as a server. Do I need to do a merge with the main branch?

**Comment by thesave** [comment]
Yep, you should be ok with pulling the update from the master, move the content to the new page, and re-issue the PR :)

**Comment by bmaschio** [comment]
@the save i think I have done it

**Comment by thesave** [comment]
Merged, thanks @bmaschio :)

**Pull request merged**
