### PR TITLE
fix broken links

### PR DESCRIPTION
**Pull request by sensorario**
I've found a couple of broken links in documentation. This is just the fix.

### CODE REVIEW

**Comment by thesave** [comment]
Hi, thanks for your contribution, you let me notice other broken links :)
However, internal links should start with `/docs/...` and end without the file extension.
For example `/docs/web-applications/web_get_post`. If you fix those I will merge ASAP!

**Comment by sensorario** [comment]
Sorry @thesave, thank you for response. In github that links works without `/docs` prefix. I think this because `docs` is the name of the repository: not a folder.

**Comment by thesave** [comment]
I scanned all our links in the documentation and many were broken.

As I could understand, the new version of Gitbook treats links in a weird (or at least unexpected) way, so that if you use an absolute path in the git repo, e.g., `/docs/some/content`, it won't be rendered verbatim in Gitbook (i.e., `gitbook-url/docs/some/content`) and instead it will link to the Github repository.

Editing from Gitbook, I noted it uses relative paths of the kind `../some/content`. However also those relative paths, pushed through git, point to the repo instead of the Gitbook.

In the end, I resorted to (and I suggest to use) absolute links of the kind `https://jolielang.gitbook.io/docs/your/page#and_anchor`.

**Comment by bmaschio** [comment]
I found an other one 

https://jolielang.gitbook.io/docs/web_applications/web_get_post

**Comment by thesave** [comment]
Thanks @bmaschio, in which document? :)

**Comment by bmaschio** [comment]
@thesave 
https://jolielang.gitbook.io/docs/web-applications/rest-apis-publication-and-integration on HTTP methods

**Comment by thesave** [comment]
Perfect, fixed, thanks :)

**Pull request closed without merging**
