### PR TITLE
Reorganization of communication port docs

### PR DESCRIPTION
**Pull request by lozingaro**
I propose to split communication ports in more then one doc, as i stated in the new summary:
* Communication Ports
    * [Introduction]
    * [Ports]
    * [Locations]
    * [Protocols]
    * [Interfaces]
    * [Data Types]
    * [Type Mismatching]
    * [Using Communication Ports]
    * [A Comprehensive Example]

In a more readable and "protocol-doc" fashion

### CODE REVIEW

**Comment by fmontesi** [comment]
Hi @stefanopiozingaro 

- Why the horizontal line at the end of some files? Is that a typo?
- Did you change any comment?
- It looks like there's a conflict with our current communication_ports.md, are you using an updated file?

@thesave Have you reviewed this?
@bmaschio Does this address (partly) your desire for a dedicated interfaces page?

Cheers,
F

**Comment by bmaschio** [comment]
@fmontesi 
Yes it does and maybe my page can go in a section on how to work with microservices.
cheers
Balint

**Comment by thesave** [comment]
I am working with @stefanopiozingaro to fix some minor issues with the pull request before merging it. We'll consider including also Balint's contribution #5 .

**Comment by fmontesi** [comment]
OK, closing then.

**Pull request closed without merging**
